[build]
  publish = "dist/kaufy"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

[functions]
  included_files = ["dist/kaufy/**"]

[functions."rendering"]
  node_bundler = "nft"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/rendering"
  status = 200

[dev]
  framework = "#custom"
  command = "npm run start"
  targetPort = 4200
  port = 8888
  publish = "dist/kaufy"
  autoLaunch = true
