[build]
  publish = "dist/kaufy/browser"
  command = "npm run build:ssr"

[build.environment]
  NODE_VERSION = "20"

[functions]
  external_node_modules = ["@angular/ssr", "express"]
  node_bundler = "nft"
  included_files = ["dist/kaufy/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/rendering"
  status = 200

[dev]
  framework = "#custom"
  command = "npm run start"
  targetPort = 4200
  port = 8888
  publish = "dist/kaufy"
  autoLaunch = true
